### ISSUE TITLE
Running rails server in development mode throws NoMethodError

### ISSUE THREAD

**Issue by stephenbinns** [gshutler/hatchet#14]
`/gems/railties-4.1.8/lib/rails/commands/server.rb:133:in `log_to_stdout': undefined method `formatter' for #<Hatchet::HatchetLogger:0x007ff828fbc980> (NoMethodError)`

https://github.com/rails/rails/blob/master/railties/lib/rails/commands/server.rb#L126

As a workaround running in daemon mode works

**Comment by gshutler** [comment]
Which version are you on? I believe this was sorted in [v0.2.5](https://github.com/gshutler/hatchet/commit/8f0221c357cac28b7a3dd99bebf592bba3df9f6c).

**Comment by stephenbinns** [comment]
Yep that works thanks!
